# Generated by Django 5.0.2 on 2024-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='tipo',
            field=models.CharField(choices=[('CASA', 'CASA'), ('APARTAMENTO', 'APARTAMENTO'), ('TERRENO', 'TERRENO'), ('PONTO COMERCIAL', 'PONTO COMERCIAL')], max_length=15),
        ),
    ]
