# Generated by Django 5.0.2 on 2024-03-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_alter_imoveis_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='locacao',
            field=models.CharField(choices=[('VENDA', 'VENDA'), ('ALUGUEL', 'ALUGUEL')], max_length=10),
        ),
    ]
